### ISSUE TITLE
Error Popup on every page.

### ISSUE THREAD

**Issue by justinweichTV** [GreenMeteor/verified#24]
{
    "url": "/index.php?r=space%2Fspace%2Fstream&cguid=ae3ae59a-70a7-4cd1-b6ff-3c0331b8263f",
    "status": 500,
    "response": "<pre>Exception 'Error' with message 'Class 'humhub\\modules\\content\\widgets\\StateBadge' not found' \n\nin /var/www/humhub/protected/modules/verified/widgets/views/wallStreamEntryHeader.php:46\n\nStack trace:\n#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require()\n#1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\\base\\View-&gt;renderPhpFile()\n#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile()\n#3 /var/www/hum...",
    "textStatus": "error",
    "xhr": {
        "readyState": 4,
        "responseText": "<pre>Exception 'Error' with message 'Class 'humhub\\modules\\content\\widgets\\StateBadge' not found' \n\nin /var/www/humhub/protected/modules/verified/widgets/views/wallStreamEntryHeader.php:46\n\nStack trace:\n#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require()\n#1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\\base\\View-&gt;renderPhpFile()\n#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile()\n#3 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(249): yii\\base\\View-&gt;render()\n#4 /var/www/humhub/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(239): yii\\base\\Widget-&gt;render()\n#5 /var/www/humhub/protected/humhub/modules/content/widgets/stream/WallStreamEntryWidget.php(223): humhub\\modules\\content\\widgets\\stream\\WallStreamEntryWidget-&gt;renderHeader()\n#6 /var/www/humhub/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(131): humhub\\modules\\content\\widgets\\stream\\WallStreamEntryWidget-&gt;renderBody()\n#7 /var/www/humhub/protected/humhub/components/Widget.php(63): humhub\\modules\\content\\widgets\\stream\\StreamEntryWidget-&gt;run()\n#8 [internal function]: humhub\\components\\Widget::widget()\n#9 /var/www/humhub/protected/humhub/modules/content/widgets/stream/StreamEntryWidget.php(91): call_user_func()\n#10 /var/www/humhub/protected/humhub/modules/stream/actions/StreamEntryResponse.php(80): humhub\\modules\\content\\widgets\\stream\\StreamEntryWidget::renderStreamEntry()\n#11 /var/www/humhub/protected/humhub/modules/stream/actions/Stream.php(415): humhub\\modules\\stream\\actions\\StreamEntryResponse::getAsArray()\n#12 /var/www/humhub/protected/humhub/modules/stream/actions/Stream.php(370): humhub\\modules\\stream\\actions\\Stream-&gt;getStreamEntryResult()\n#13 /var/www/humhub/protected/humhub/modules/stream/actions/Stream.php(349): humhub\\modules\\stream\\actions\\Stream-&gt;addResponseEntries()\n#14 [internal function]: humhub\\modules\\stream\\actions\\Stream-&gt;run()\n#15 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Action.php(93): call_user_func_array()\n#16 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\\base\\Action-&gt;runWithParams()\n#17 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\\base\\Controller-&gt;runAction()\n#18 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\\base\\Module-&gt;runAction()\n#19 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\\web\\Application-&gt;handleRequest()\n#20 /var/www/humhub/index.php(25): yii\\base\\Application-&gt;run()\n#21 {main}</pre>",
        "status": 500,
        "statusText": "Internal Server Error"
    },
    "dataType": "html",
    "html": "<pre>Exception 'Error' with message 'Class 'humhub\\modules\\content\\widgets\\StateBadge' not found' \n\nin /var/www/humhub/protected/modules/verified/widgets/views/wallStreamEntryHeader.php:46\n\nStack trace:\n#0 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(347): require()\n#1 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\\base\\View-&gt;renderPhpFile()\n#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\\base\\View-&gt;renderFile()\n#3 /var/www/hum...",
    "error": {},
    "errorThrown": "Internal Server Error",
    "validationError": false
}

**Comment by felixhahnweilheim** [comment]
Are you using HumHub version 1.13 or lower?
An upgrade to 1.14 should solve your issue.

@ArchBlood  I think the HumHub minVersion for beta3 should have been 1.14 (because we added the wall stream view which uses the StateBadge widget introduced in 1.14).

**Comment by ArchBlood** [comment]
> Are you using HumHub version 1.13 or lower? An upgrade to 1.14 should solve your issue.
> 
> @ArchBlood I think the HumHub minVersion for beta3 should have been 1.14 (because we added the wall stream view which uses the StateBadge widget introduced in 1.14).

See the following commit https://github.com/GreenMeteor/verified/commit/c9921dd9a322b8a373cb89b7024f70432aadfdd3

**Comment by justinweichTV** [comment]
I see, yes Im using 1.13 I'm update it later Thanks 👍

**Comment by felixhahnweilheim** [comment]
@ArchBlood Please see my commit comment.
